language: android
sudo: true
android:
  components:
    - tools
    - platform-tools
    - android-27
    - sys-img-x86-android-27
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  before-install:
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "platforms;android-28"
  before_script:
    - echo no | android create avd --force -n test -t android-27 --abi x86 -c 200M
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
  script:
    - ./gradlew build :library:test :app:connectedDebugAndroidTest